### ISSUE TITLE
Gephi Application Report

### ISSUE THREAD

**Issue by bbengfort** [bbengfort/printing-press#1]
@KonstantinosX -- I've created a stub in Github for our Gephi paper, you can find it here: [Gephi Application Report](https://github.com/bbengfort/printing-press/tree/master/drafts/coursework/CMSC734/gephi-application-report)

I've created the paper structure, gave suggestions for the three headlines we should explore, and even found a bunch of references and added them in summary in the introduction. We should be good to go to getting this paper done quickly!

**Comment by KonstantinosX** [comment]
@bbengfort Got my graph extracted and like yours and kinda did clustering. Can't figure out Edge bundling. I spent a bunch of time with gephi today...I'm kinda ready to critique it as well lol. Talk to you tommorow

**Comment by bbengfort** [comment]
@KonstantinosX ha - ok; sorry it didn't go so well. I'm working on the 734 project, but can do some Gephi stuff later today.

**Comment by KonstantinosX** [comment]
@bbengfort Been dicking around with gephi a lot. I think I've set up two of the three headlines. I pushed my ideas as comments in the tex file. I think these will be nice. I have found out how to do all of them and have done it for my own network. I will send you an email with the images after i come back from lunch.

**Comment by KonstantinosX** [comment]
@bbengfort I started working on the intro, the dataset description and the two headlines. Just letting you know in case you start working on this, just so that our work doesn't overlap.

**Comment by KonstantinosX** [comment]
@bbengfort Put my finishing touches on the final draft and filled in the conclusion. I had made a mistake in the betweenness centrality graphs where the node size was actually the betweenness centrality as well as the color. I changed it and re-rendered the images and now the size signifies the node degree. Feel free to change anything in the insight text for that section because I'm not sure if I understood exactly what you were getting at. Other than that the last citation is lonely on the last page. I'm okay with that and do not think it matters because I am evil. If you do and want to change that feel free to remove anything and give that last citation some company.

**Comment by bbengfort** [comment]
@KonstantinosX I just did a pull, but I still see no conclusion? Can you do a push, you didn't branch did you?

**Comment by bbengfort** [comment]
@KonstantinosX Never mind! I accidentally typo'd and the build failed, so I ended up opening an old version of the PDF, which is why I couldn't see the conclusion - all set now!

**Comment by bbengfort** [comment]
Ok - final draft up; made a few changes and cleaned it up; posting now!
